In [1]:
import numpy
import itertools
from Bio.Seq import Seq
from Bio.Alphabet import IUPAC
from Bio import SeqIO
from Bio.SeqUtils.ProtParam import ProteinAnalysis
from scipy import stats
from Bio.Alphabet import IUPAC
#from itertools import permutations

AA=["A","C","D","E","F","G","H","I","K","L","M","N","P","Q","R","S","T","V","W","Y"]
SC=["1","2","3","4","5","6","7"]


### Side chain
original  
ACDEFGHIKLMNPQRSTVWY  
12445131311222322155




In [2]:
dipep = [''.join(i) for i in itertools.product(AA, repeat = 2)]
di_sc = [''.join(i) for i in itertools.product(SC, repeat = 3)]
print(di_sc)

['111', '112', '113', '114', '115', '116', '117', '121', '122', '123', '124', '125', '126', '127', '131', '132', '133', '134', '135', '136', '137', '141', '142', '143', '144', '145', '146', '147', '151', '152', '153', '154', '155', '156', '157', '161', '162', '163', '164', '165', '166', '167', '171', '172', '173', '174', '175', '176', '177', '211', '212', '213', '214', '215', '216', '217', '221', '222', '223', '224', '225', '226', '227', '231', '232', '233', '234', '235', '236', '237', '241', '242', '243', '244', '245', '246', '247', '251', '252', '253', '254', '255', '256', '257', '261', '262', '263', '264', '265', '266', '267', '271', '272', '273', '274', '275', '276', '277', '311', '312', '313', '314', '315', '316', '317', '321', '322', '323', '324', '325', '326', '327', '331', '332', '333', '334', '335', '336', '337', '341', '342', '343', '344', '345', '346', '347', '351', '352', '353', '354', '355', '356', '357', '361', '362', '363', '364', '365', '366', '367', '371', '372', '373'

In [3]:
f_num=350
myseq="AILMVNQSTGPCHKPDEFWY"
trantab2=myseq.maketrans("AILMVNQSTGPCHKPDEFWY","11111222233455566777")
arr = numpy.empty((0,f_num), dtype=numpy.float)
class_arr = numpy.empty((0), dtype=numpy.int)
#print(arr.shape)
#print(arr)
all_fasta=("../major_capsid.fasta","../minor_capsid.fasta","../baseplate.fasta",
          "../major_tail.fasta","../minor_tail.fasta","../portal.fasta",
          "../tail_fiber.fasta","../tail_sheath.fasta","../collar.fasta",
          "../htj.fasta")
#print(all_fasta)
prot_class=0;
for file in all_fasta:
    print('####################' + file)
    for record in SeqIO.parse(file, "fasta"):
        #print(record.id)
        ll=len(record.seq)
        #xx=Seq(str(record.seq),IUPAC.protein)
        X = ProteinAnalysis(record.seq.__str__().replace('X','A').replace('J','L'))
        #X = ProteinAnalysis(str(xx))
        tt= [X.isoelectric_point(), X.instability_index(),ll,X.aromaticity(),
            X.molar_extinction_coefficient()[0],X.molar_extinction_coefficient()[1],
            X.gravy()]
        tt_n = numpy.asarray(tt,dtype=numpy.float)
        myseq=str(record.seq).translate(trantab2)
        dipep_count=[myseq.count(i)/ll for i in di_sc]
        dipep_count_n = numpy.asarray(dipep_count,dtype=numpy.float)
    
        cat_n= numpy.append(dipep_count_n,tt_n)
        cat_n = cat_n.reshape((1,cat_n.shape[0]))

        arr = numpy.append(arr,cat_n , axis=0)
        class_arr = numpy.append(class_arr,prot_class)
    prot_class+=1
    

    

####################../major_capsid.fasta
####################../minor_capsid.fasta
####################../baseplate.fasta
####################../major_tail.fasta
####################../minor_tail.fasta
####################../portal.fasta
####################../tail_fiber.fasta
####################../tail_sheath.fasta
####################../collar.fasta
####################../htj.fasta


In [4]:
 print(arr.shape)

#arr_z = numpy.apply_over_axis(stats.zscore,arr,0)
arr_z=numpy.apply_along_axis(stats.zscore,0,arr)
#arr_z=numpy.apply_along_axis(stats.zscore,0,arr)
#print(arr_z)
#print(arr)
#print(arr_z.shape)
#print(prot_class)

(25675, 350)


In [5]:
mean_arr=numpy.apply_along_axis(numpy.mean,0,arr)
#print(mean_arr)
print(mean_arr.shape)
std_arr=numpy.apply_along_axis(numpy.std,0,arr)
print(std_arr.shape)

(350,)
(350,)


In [6]:
#targets = numpy.array([[2, 3, 4, 0]]).reshape(-1)

nb_classes = 10
one_hot_targets = numpy.eye(nb_classes)[class_arr]
print(one_hot_targets)
print(one_hot_targets.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
(25675, 10)


In [7]:

final = numpy.concatenate((arr_z, one_hot_targets), axis=1)
final_raw = numpy.concatenate((arr, one_hot_targets), axis=1)

In [ ]:
#numpy.savetxt('test.out', final, delimiter='\t') 
#numpy.savetxt('test2.out', final_raw, delimiter='\t') 

In [8]:
numpy.random.shuffle(final)
numpy.random.shuffle(final_raw)

In [9]:
import pickle
##number of proteins for training
tt=25000
##number of features

pickle.dump(final[0:tt,0:f_num], open( "di_sc_train_x.p", "wb" ) )
pickle.dump(final[tt:,0:f_num],  open( "di_sc_test_x.p" , "wb" ) )
pickle.dump(final[0:tt,f_num:], open( "di_sc_train_y.p", "wb" ) )
pickle.dump(final[tt:,f_num:],  open( "di_sc_test_y.p" , "wb" ) )
pickle.dump(mean_arr,  open( "di_sc_mean.p" , "wb" ) )
pickle.dump(std_arr,  open( "di_sc_std.p" , "wb" ) )

In [ ]:
#pickle.dump(final_raw[0:tt,0:f_num], open( "dipep_raw_new_train_x.p", "wb" ) )
#pickle.dump(final_raw[tt:,0:f_num],  open( "dipep_raw_new_test_x.p" , "wb" ) )
#pickle.dump(final_raw[0:tt,f_num:], open( "dipep_raw_new_train_y.p", "wb" ) )
#pickle.dump(final_raw[tt:,f_num:],  open( "dipep_raw_new_test_y.p" , "wb" ) )