In [1]:
#load the saved matrices
import pickle
train_X=pickle.load(open( "train_x.p", "rb" ) )
test_X=pickle.load(open( "test_x.p", "rb" ) )
train_Y=pickle.load(open( "train_y.p", "rb" ) )
test_Y=pickle.load(open( "test_y.p", "rb" ) )

In [2]:
#import keras and numpy
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Activation


/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/matplotlib/__init__.py:962: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #2
  (fname, cnt))
/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/matplotlib/__init__.py:962: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #3
  (fname, cnt))


In [3]:
#this list the devices, just making sure there is a GPU present, you might be fine with no GPU
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 16510920327338495873
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 3832020992
locality {
  bus_id: 1
}
incarnation: 1923186097697208606
physical_device_desc: "device: 0, name: GRID K520, pci bus id: 0000:00:03.0, compute capability: 3.0"
]


In [4]:
#model with 2 leyers of 100 LSTM neurons
model = Sequential()
model.add(LSTM(100,return_sequences=True,input_shape=[7,1]))
model.add(LSTM(100))
model.add(Dense(3,activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 7, 100)            40800     
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 303       
Total params: 121,503
Trainable params: 121,503
Non-trainable params: 0
_________________________________________________________________
None


In [5]:
#fit the model
model.fit(train_X, train_Y, epochs=10, batch_size=2)

Epoch 1/10
7/7 [==============================] - 1s 137ms/step - loss: 0.6639 - acc: 0.6667
Epoch 2/10
7/7 [==============================] - 0s 20ms/step - loss: 0.6520 - acc: 0.6667
Epoch 3/10
7/7 [==============================] - 0s 21ms/step - loss: 0.6358 - acc: 0.6667
Epoch 4/10
7/7 [==============================] - 0s 20ms/step - loss: 0.6341 - acc: 0.6667
Epoch 5/10
7/7 [==============================] - 0s 21ms/step - loss: 0.6372 - acc: 0.6667
Epoch 6/10
7/7 [==============================] - 0s 21ms/step - loss: 0.6347 - acc: 0.6667
Epoch 7/10
7/7 [==============================] - 0s 20ms/step - loss: 0.6248 - acc: 0.7143
Epoch 8/10
7/7 [==============================] - 0s 21ms/step - loss: 0.6205 - acc: 0.6667
Epoch 9/10
7/7 [==============================] - 0s 21ms/step - loss: 0.6196 - acc: 0.6667
Epoch 10/10
7/7 [==============================] - 0s 20ms/step - loss: 0.6241 - acc: 0.6667


In [6]:
#use the model to predict
print(test_Y)
print(model.predict(test_X))

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0.3040119  0.41515192 0.28083614]
 [0.30961195 0.394492   0.29589605]
 [0.32045424 0.38646588 0.29307988]
 [0.3144113  0.38941556 0.29617307]]


In [7]:
# Final evaluation of the model
scores = model.evaluate(test_X, test_Y, verbose=1)
print("Accuracy: %.2f%%" % (scores[1]*100))

4/4 [==============================] - 0s 34ms/step
Accuracy: 66.67%


In [8]:
#you can save the as a file so you dont have to train it every time
model.save('my_model.h5')